# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'docs|.git|.tox'
default_stages: [ commit ]

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
            -   id: check-yaml
            -   id: check-case-conflict
            -   id: check-merge-conflict
            -   id: check-symlinks
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml

    - repo: https://github.com/hadialqattan/pycln
      rev: v2.1.2
      hooks:
          - id: pycln
            args: [--config=pyproject.toml]

    - repo: https://github.com/pycqa/bandit
      rev: 1.7.4
      hooks:
          - id: bandit
            exclude: "test_*"
            args: ["-iii", "-ll", "-s=B308,B703", "-q"]

    -   repo: https://github.com/asottile/blacken-docs
        rev: v1.12.1
        hooks:
          -   id: blacken-docs
              additional_dependencies: [black]

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'v0.991'
        hooks:
            -   id: mypy
                args: [ --config-file, pyproject.toml ]

    -   repo: https://github.com/myint/docformatter.git
        rev: v1.5.1
        hooks:
            -   id: docformatter
                args: [ '--in-place', '--wrap-summaries=120', '--wrap-descriptions=120', '--pre-summary-newline' ]

    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.1.7
        hooks:
            -   id: ruff
                args: [ --fix ]
            -   id: ruff-format
