# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'docs|.git|.tox'
default_stages: [ commit ]

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
            -   id: check-yaml
            -   id: check-case-conflict
            -   id: check-merge-conflict
            -   id: check-symlinks
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml

    -   repo: https://github.com/pycqa/isort
        rev: 5.11.4
        hooks:
            -   id: isort
                name: isort (python)
                args: [ --settings-path=pyproject.toml ]

    -   repo: https://github.com/psf/black.git
        rev: 22.12.0
        hooks:
            -   id: black
                args: [ --config=pyproject.toml ]

    -   repo: https://github.com/asottile/blacken-docs
        rev: v1.12.1
        hooks:
          -   id: blacken-docs
              additional_dependencies: [black]

    -   repo: https://github.com/humitos/mirrors-autoflake.git
        rev: v1.1
        hooks:
            -   id: autoflake
                args: [ '--in-place', '--remove-all-unused-imports', '--remove-unused-variable' ]

    -   repo: https://github.com/pycqa/flake8
        rev: 6.0.0
        hooks:
            -   id: flake8

    -   repo: https://github.com/myint/docformatter.git
        rev: v1.5.1
        hooks:
            -   id: docformatter
                args: [ '--in-place', '--wrap-summaries=120', '--wrap-descriptions=120', '--pre-summary-newline' ]

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'v0.991'
        hooks:
            -   id: mypy
                args: [ --config-file, pyproject.toml ]
