dist: xenial
language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install poetry
    - poetry install --extras full

script:
    - scripts/test

after_script:
    - pip install codecov
    - codecov
