[project]
name = "mailers"
version = "3.4.0"
description = "Email delivery for asyncio."
authors = [{ name = "Alex Oleshkevich", email = "alex.oleshkevich@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
keywords = ["asyncio", "email", "mailer", "mail"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "anyio>=3.7.1",
]

[project.optional-dependencies]
jinja2 = ["jinja2>=3.1.6"]
smtp = ["aiosmtplib>=5.1.1"]
dkim = ["dkimpy>=1.1.8"]
css_inline = ["css-inline>=0.21.0"]

[project.urls]
Homepage = "https://github.com/alex-oleshkevich/mailers"
Repository = "https://github.com/alex-oleshkevich/mailers"
Documentation = "https://github.com/alex-oleshkevich/mailers"

[project.entry-points.pytest11]
mailers = "mailers.pytest_plugin"

[build-system]
requires = ["uv_build>=0.11.30,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "mailers"
module-root = ""

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-asyncio>=1.4.0",
    "aiosmtpd>=1.4.6",
    "pytest-sugar>=1.1.1",
    "pytest-cov>=7.1.0",
    "mypy>=2.3.0",
    "prek>=0.4.10",
    "dkimpy>=1.1.8",
    "jinja2>=3.1.6",
    "aiosmtplib>=5.1.1",
    "css-inline>=0.21.0",
]

# required in case a parent directory overrides these options
[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"

[tool.coverage.run]
branch = true
source = ["mailers"]
omit = ["tests/*", ".venv/*", "*/__main__.py", "examples/*"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "if typing.TYPE_CHECKING:",
]

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
files = ["mailers", "tests"]
exclude = "/*venv/"
pretty = true
show_error_context = true
show_column_numbers = true
show_error_codes = true

[tool.ruff]
exclude = [".egg", ".git", ".hg", ".mypy_cache", ".nox", ".tox", ".venv"]
line-length = 120
indent-width = 4

[tool.ruff.lint]
fixable = ["ALL"]

[tool.ruff.format]
skip-magic-trailing-comma = false
