#!/bin/sh -e

export PKG="mailers"
export PREFIX=""

if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

set -x

${PREFIX}black ${PKG} tests
${PREFIX}isort \
  --multi-line=3 \
  --trailing-comma \
  --force-grid-wrap=0 \
  --combine-as \
  --line-width 88 \
  --recursive \
  --apply ${PKG} tests

${PREFIX}mypy ${PKG} --ignore-missing-imports --disallow-untyped-defs
