#!/bin/sh -e

export PKG='mailers'
export VERSION=`cat ${PKG}/__init__.py | grep __version__ | sed "s/__version__ = //" | sed "s/'//g" | sed 's/"//g'`

echo "Publishing ${PKG}==${VERSION}"

find ${PKG} -type f -name "*.py[co]" -delete
find ${PKG} -type d -name __pycache__ -delete

sed -i "s/^version = .*/version = \"${VERSION}\"/g" pyproject.toml
poetry publish --build

echo ""
echo "You probably want to also tag the version now:"
echo "git add pyproject.toml"
echo "git ci pyproject.toml -m 'Version ${VERSION}'"
echo "git tag -a ${VERSION} -m 'Version ${VERSION}'"
echo "git push --tags"
