#!/bin/sh -e

export PKG='mailers'
export VERSION=`cat ${PKG}/__init__.py | grep __version__ | sed "s/__version__ = //" | sed "s/'//g"`

echo "Publishing ${PKG} ${VERSION}"

find ${PKG} -type f -name "*.py[co]" -delete
find ${PKG} -type d -name __pycache__ -delete

sed -i "s/^version = .*/version = \"${VERSION}\"/g" pyproject.toml
poetry build

echo "Tag and commit a new version."

#git tag -a ${VERSION} -m "Release ${VERSION}"
#git push --tags
