#!/bin/sh

export PKG=mailers
export PREFIX=""
if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi


${PREFIX}pytest --ignore .venv \
  -W ignore::DeprecationWarning \
  --cov=${PKG} \
  --cov=tests \
  --cov-fail-under=100 \
  --cov-report=term-missing \
  ${@} tests/
