name: Upload Python Package

on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
    publish_package:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   uses: actions/checkout@v7.0.1
            -   uses: astral-sh/setup-uv@v8.3.2
                with:
                    version: '0.11.30'
            -   name: Build
                run: uv build --no-sources
            -   name: Publish
                env:
                    UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
                run: uv publish
